{{- if .Values.externalSecrets.enabled }}
{{- $syncSource := .Values.syncSource | required "neither 'ldap' nor 'azure' is not configured as the syncSource" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ytsaurus-identity-sync.fullname" . }}
  labels:
    {{- include "ytsaurus-identity-sync.labels" . | nindent 4 }}
spec:
  data:
    - remoteRef:
        key: {{ required "externalSecretID is not set" .Values.externalSecrets.ytsaurusSecretID }}
        property: YT_TOKEN
      secretKey: YT_TOKEN
    {{- if eq $syncSource "ldap" }}
    - remoteRef:
        key: {{ required "externalSecretID is not set" .Values.externalSecrets.sourceSecretID }}
        property: LDAP_PASSWORD
      secretKey: LDAP_PASSWORD
    {{- else if eq $syncSource "azure" }}
    - remoteRef:
        key: {{ required "externalSecretID is not set" .Values.externalSecrets.sourceSecretID }}
        property: AZURE_CLIENT_SECRET
      secretKey: AZURE_CLIENT_SECRET
    {{- end }}
  secretStoreRef:
    kind: {{ required "secretStore kind is not set" .Values.externalSecrets.secretStore.kind }}
    name: {{ required "secretStore name is not set" .Values.externalSecrets.secretStore.name }}
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: {{ include "ytsaurus-identity-sync.fullname" . }}
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
{{- end }}
