{{- if .Values.plainSecrets.enabled }}
{{- $syncSource := .Values.syncSource | required "neither 'ldap' nor 'azure' is not configured as the syncSource" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ytsaurus-identity-sync.fullname" . }}
  labels:
    {{- include "ytsaurus-identity-sync.labels" . | nindent 4 }}
data:
  YT_TOKEN: {{ required "YT_TOKEN is not provided" .Values.yt.token | b64enc | quote }}
  {{- if eq $syncSource "ldap" }}
  LDAP_PASSWORD: {{ required "LDAP_PASSWORD is not provided" .Values.ldap.password | b64enc | quote }}
  {{- else if eq $syncSource "azure" }}
  AZURE_CLIENT_SECRET: {{ required "AZURE_CLIENT_SECRET is not provided" .Values.azure.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
